# =============================================
# Common Application Properties
# =============================================
spring.application.name=inventory_tracker

# Default active profile
spring.profiles.active=dev

# Thymeleaf
spring.thymeleaf.cache=false
